[env]
FREETYPE_PROPERTIES = "cff:no-stem-darkening=0"

[colors.primary]
background = "#23262e"
foreground = "#d5dae9"

[colors.cursor]
cursor = "#1c9969"
text = "#23262e"

[colors.normal]
black = "#38425a"
red = "#cf6950"
green = "#1c9969"
yellow = "#aa7f2c"
blue = "#8075f5"
magenta = "#d95a88"
cyan = "#3790b3"
white = "#7486b2"

[colors.bright]
black = "#465476"
red = "#e9b5a8"
green = "#8dcfad"
yellow = "#d9bd95"
blue = "#c5b8fb"
magenta = "#f1afc2"
cyan = "#9cc7dd"
white = "#b8c0da"

[cursor]
thickness = 0.25

[font]
size = 9

[font.normal]
family = "Sono"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mods = "Control|Shift"

[window.padding]
x = 4
y = 4
