#!/bin/env bash

set -o errexit -o nounset

export PATH=~/.ghcup/bin:$PATH

GHCUP=~/.ghcup/bin/ghcup

${GHCUP} run cabal build

bin="$(${GHCUP} run cabal list-bin xmonad)"

if [ -n "${1-}" ] && [ -f "${bin}" ]
then
  echo "Install Binary into $1"
  install "${bin}" "$1"
fi
